<?php
/**
 * Terms and Conditions
 *
 * This file outlines the terms of conditions for the web application.
 *
 * @package public/terms
 */

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms of Service</title>
    <link rel="stylesheet" href="/css/main.css">
    <link rel="stylesheet" href="/css/layout/footer.css">
    <link rel="stylesheet" href="/css/pages/terms.css">
</head>
<body>
<header>
    <h1>Terms and Conditions</h1>
</header>
<main>
    <section>
        <h2>Acceptance of Terms</h2>
        <p>By accessing or using our services, you agree to be bound by these <strong onclick="location.href='terms_and_conditions.php'">Terms and Conditions</strong>. If you do not agree to these terms, you may not use our services.</p>
    </section>
    <section>
        <h2>Modifications to Terms</h2>
        <p>We reserve the right to modify these terms at any time. Any changes will be effective immediately upon posting on our website. Your continued use of our services after any changes indicates your acceptance of the new terms.</p>
    </section>
    <section>
        <h2>User Responsibilities</h2>
        <p>You can do whatever you want with your account, we are not responsible for any actions taken by you or any third party using your account. You are responsible for maintaining the confidentiality of your account information and for all activities that occur under your account.</p>
        <p>If you attempt to hack or gain unauthorized access to our service... <i>Do it if you wish, I don't care. but plz tell me how you did it, I wanna know what I did wrong. 👀</i></p>
    </section>
    <section>
        <h2>Termination</h2>
        <p>We reserve the right to suspend or terminate your access to our services at any time, without notice, because I want to.</p>
        <p>We are not responsible for any loss of data or other consequences resulting from the termination of your account.</p>
    </section>
    <section>
        <h2>You have no rights here</h2>
        <p>By using our services, you acknowledge that you have no rights to any content or data generated through our services. All rights are reserved by us.</p>
        <p>We are not responsible for any content generated by users, and we reserve the right to remove any content that violates these terms or is otherwise objectionable.</p>
    </section>
    <section>
        <h2>I know what you did</h2>
        <p>I know that you didn't read these terms and conditions. And just checked the box saying that you did.</p>
        <p>So I can write whatever I want here, and you will still have to accept it.</p>
    </section>
    <section>
        <h2>I am smarter than you</h2>
        <p>By using our services, you acknowledge that I am smarter than you. I know what I'm doing, and you don't.</p>
        <p>Any attempts to outsmart me will result in immediate termination of your account and possible legal action.</p>
        <p>So, don't even try it. Just accept that I am the smartest person in the world and move on.</p>
    </section>
    <section>
        <h2><span onclick="location.href='terms_of_service.php'">Terms of Service</span> & <span onclick="location.href='terms_of_use.php'">Terms of Use</span></h2>
        <p>These <strong onclick="location.href='terms_of_service.php'">Terms of Service</strong> and <strong onclick="location.href='terms_of_use.php'">Terms of Use</strong> are separate documents. By using our services, you agree to both documents.</p>
        <p>If you do not agree to either document, you not accept these terms and conditions, and if you do not agree to these terms and conditions, you may not use our services.</p>
    </section>
    <section>
        <h2>LICENSE</h2>
        <p>And also we have a <a href="https://github.com/DanyilT/WebDev-Project/blob/main/LICENSE">license</a> for this project. But I don't think it for you.</p>
    </section>
    <?php include 'index.php'; ?>
</main>

<?php include '../layout/footer.php'; ?>
