name: Create Config

on:
  workflow_dispatch:

jobs:
  create-config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create config.php
      run: |
        echo "<?php" > config.php
        echo "return [" >> config.php
        echo "    'host' => '${{ secrets.DB_HOST }}'," >> config.php
        echo "    'dbname' => '${{ secrets.DB_NAME }}'," >> config.php
        echo "    'user' => '${{ secrets.DB_USER }}'," >> config.php
        echo "    'password' => '${{ secrets.DB_PASSWORD }}'," >> config.php
        echo "    'options' => [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]," >> config.php
        echo "];" >> config.php
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    - name: Upload config.php as artifact
      uses: actions/upload-artifact@v4
      with:
        name: config
        path: config.php
